sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker exec -it 88861f57a3a8 bash
  # - docker-compose exec --env 'RAILS_ENV=test' backend bundle install
  # - docker-compose exec --env 'RAILS_ENV=test' backend rails db:create
  # - docker-compose exec --env 'RAILS_ENV=test' backend rails db:migrate
  # - docker-compose exec --env 'RAILS_ENV=test' backend rails test
