version: "3"

volumes:
  db-data:

services:
  db:
    container_name: minwari-backend_db_1
    image: mysql:5.7
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"

  backend:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ".:/minwari-backend"
    depends_on:
      - db
    links:
      - db
    environment:
      FRONTEND_ORIGIN: "http://localhost:3000"
    tty: true
    stdin_open: true
